# Generated by Django 4.1.5 on 2023-01-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bug_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BugApi",
        ),
    ]
